spring:
  application:
    name: monitoring
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: monitoring
      properties:
        state.dir: data

server:
  host: localhost
  port: 8080