spring:
  application:
    name: tweets
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: leaderboard
      bootstrap-servers: localhost:9092
      properties:
        schema.registry.url: http://localhost:8081
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde