spring:
  application:
    name: leaderboard
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: leaderboard
      properties:
        state.dir: data

server:
  host: localhost
  port: 8080